# frozen_string_literal: true

require "minitest/autorun"
require "digest"
require "fileutils"
require "tmpdir"
require "enola"

module FakeRelease
  SCRIPT = <<~SH
    #!/bin/sh
    case "$1" in
      --version) echo "enola version VERSION"; exit 0 ;;
      providers)
        case "$2" in
          fetch) echo "rubydex VERSION fetched"; exit 0 ;;
          list) echo "  rubydex  0.4.0 at /nowhere/librubydex_sys.so"; exit 0 ;;
        esac
        echo "Usage: enola providers"; exit 2 ;;
      constraints|check|plan) echo "Usage: enola $1"; exit 2 ;;
      hook) echo 'unknown command "hook" (expected one of: check)'; exit 1 ;;
      fail) exit 3 ;;
      echo) shift; echo "$@"; exit 0 ;;
    esac
    exit 0
  SH

  def self.build(root, platform:, version: Enola::UPSTREAM_VERSION, prefix: "enola", checksum: nil)
    release = File.join(root, "v#{version}")
    FileUtils.mkdir_p(release)
    Dir.mktmpdir do |stage|
      name = "#{prefix}-#{version}-#{platform}"
      File.write(File.join(stage, name), SCRIPT.sub("VERSION", version))
      FileUtils.chmod(0o755, File.join(stage, name))
      File.write(File.join(stage, "LICENSE"), "license")
      system("tar", "czf", File.join(release, "#{name}.tar.gz"), "-C", stage, name, "LICENSE", exception: true)
    end
    tarball = File.join(release, "#{prefix}-#{version}-#{platform}.tar.gz")
    digest = checksum || Digest::SHA256.file(tarball).hexdigest
    File.write(File.join(release, "#{prefix}-#{version}-#{platform}.sha256"), "#{digest}  #{File.basename(tarball)}\n")
    "file://#{root}"
  end

  # A RubyGems-generated binstub, verbatim in shape: the /bin/sh + `ruby -x`
  # polyglot preamble RubyGems writes, then the Ruby half that activates the gem.
  # The preamble is the point — it carries the interpreter's absolute path, so
  # `Gem.activate_bin_path` lands several hundred bytes into the file rather than
  # near its start.
  def self.gem_binstub(dir, name = "enola", interpreter: "/usr/local/lib/ruby/gems/3.4.0/bin/ruby")
    FileUtils.mkdir_p(dir)
    path = File.join(dir, name)
    File.write(path, <<~STUB)
      #!/bin/sh
      # -*- ruby -*-
      _=_\
      =begin
      bindir="${0%/*}"
      ruby="$bindir/ruby"
      if [ ! -f "$ruby" ]; then
        ruby="ruby"
      fi
      exec "$ruby" "-x" "$0" "$@"
      =end
      #!#{interpreter}
      #
      # This file was generated by RubyGems.
      #
      # The application '#{name}' is installed as part of a gem, and
      # this file is here to facilitate running it.
      #

      require 'rubygems'

      Gem.use_gemdeps

      version = ">= 0.a"

      str = ARGV.first
      if str
        str = str.b[/\A_(.*)_\z/, 1]
        if str and Gem::Version.correct?(str)
          version = str
          ARGV.shift
        end
      end

      if Gem.respond_to?(:activate_bin_path)
      load Gem.activate_bin_path('#{name}', '#{name}', version)
      else
      gem "#{name}", version
      load Gem.bin_path("#{name}", "#{name}", version)
      end
    STUB
    FileUtils.chmod(0o755, path)
    path
  end

  # A version manager's shim carries none of the markers a binstub does: it is
  # a shell script that re-execs the same command through the manager. rbenv
  # and asdf write one for every gem executable installed.
  def self.shim(dir, name = "enola")
    FileUtils.mkdir_p(dir)
    path = File.join(dir, name)
    File.write(path, <<~SHIM)
      #!/usr/bin/env bash
      set -e
      [ -n "$RBENV_DEBUG" ] && set -x
      program="#{name}"
      export RBENV_ROOT="/home/someone/.rbenv"
      exec rbenv exec "$program" "$@"
    SHIM
    FileUtils.chmod(0o755, path)
    path
  end

  def self.binary(dir, version)
    FileUtils.mkdir_p(dir)
    path = File.join(dir, "enola")
    File.write(path, SCRIPT.sub("VERSION", version))
    FileUtils.chmod(0o755, path)
    path
  end
end

class EnolaTest < Minitest::Test
  PLATFORM = "linux-amd64"

  def setup
    @tmp = Dir.mktmpdir("enola-test")
    @cache = File.join(@tmp, "cache")
    @release_base = FakeRelease.build(File.join(@tmp, "releases"), platform: PLATFORM)
    @channel = Enola::Channel.new(name: "upstream", release_base: @release_base, version: Enola::UPSTREAM_VERSION, asset_prefix: "enola")
  end

  def teardown
    FileUtils.rm_rf(@tmp)
  end

  def fetcher(channel = @channel)
    Enola::Fetcher.new(channel: channel, cache_root: @cache, platform: PLATFORM)
  end

  def resolver(channel: @channel, path: "")
    Enola::Resolver.new(channel: channel, cache_root: @cache, platform: PLATFORM, path: path)
  end

  def unreachable
    Enola::Channel.new(name: "upstream", release_base: "file://#{@tmp}/missing", version: Enola::UPSTREAM_VERSION, asset_prefix: "enola")
  end
end
